FishMash/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'languages/index'
  end

  get 'api' => 'application#api'
  namespace :api, defaults: {format: :json} do
    resources :exams, except: [:create, :delete, :update] do
      post 'start'
      post 'get_question'
      post 'answer'
      get 'summary'
    end
    resources :lists, only: [:index, :show] do
      post 'add'
      post 'remove'
    end
    resources :words, only: [:create]
    resources :languages, only: [:index]
    resources :users do
      collection do
        post 'authenticate'
        post 'set_password'
      end
    end
  end

  resources :wordlists, controller: 'word_lists'
  resources :exams, only: [:index, :new, :create] do
    get 'begin'
    post 'start'
    get 'answer'
    post 'answer', to: 'exams#save_answer'
    get 'summary'
    get 'learn'
    get 'stats'
    post 'get_stats/:class_id', to: 'exams#get_stats'
  end
  resources :users, only: [:show, :create] do
    collection do
      get 'login'
      post 'authenticate'
      get 'logout'
      get 'register'
      get 'profile'
    end

    post 'set_password'
  end
  resources 'classes', except: [:show] do
    post 'add_member'
    post 'remove_member'
  end
  root 'home#index'

end

FishMash/app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :require_login
  before_action :require_teacher

  # Displays all classes in the system
  def index
    @classes = StudentClass.where(owner_id: get_logged_user.id)
  end

  def new

  end

  def create
    stud_class = StudentClass.new(class_params)
    stud_class.owner = get_logged_user
    if stud_class.save
      redirect_to edit_class_path(stud_class)
    else
      flash[:errors] = stringify_errors(stud_class)
      redirect_to new_class_path and return
    end
  end

  def edit
    @student_class = StudentClass.find(params[:id])
  end

  def update
    @student_class = StudentClass.find(params[:id])
    if !@student_class.update(class_params)
      flash[:errors] = stringify_errors(@student_class)
      redirect_to edit_class_path(@student_class) and return
    end

    render 'edit'
  end

  def add_member
    @student_class = StudentClass.find params[:class_id]

    login_to_find = params[:member_new][:login]
    disallow_find = false

    if login_to_find.blank?
      disallow_find = true
      flash[:errors] = "You have to type in the login first."
    end

    student_to_add = User.find_by(login: params[:member_new][:login])
    if student_to_add.nil?
      disallow_find = true
      flash[:errors] = "User with such login does not exist."
    end

    if disallow_find
      redirect_to edit_class_path(@student_class)
    else
      @student_class.users.push student_to_add if !@student_class.users.include?(student_to_add)
      if !@student_class.save
        flash[:errors] = stringify_errors(@student_class)
        redirect_to edit_class_path(@student_class)
      else
        render 'edit'
      end
    end
  end

  def remove_member
    @student_class = StudentClass.find params[:class_id]
    @student_to_remove = User.find params[:user_id]

    if @student_to_remove.nil? or @student_class.nil?
      flash[:errors] = "User or class with such ID does not exist."
    else
      student_membership = StudentClassMembership.find_by(user_id: @student_to_remove.id, student_class_id: @student_class.id)
      student_membership.destroy
    end
    redirect_to edit_class_path(@student_class)
  end

  private
    def class_params
      params.require(:student_class).permit(:description, :name)
    end
end

FishMash/app/helpers/classes_helper.rb
module ClassesHelper
end

FishMash/app/views/classes/edit.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-2"></div>
<div class="col-md-8">
  <div class="col-md-8">
    <h2 class="fish-h2">Details</h2>
    <%= form_for @student_class, url: class_path(@student_class) do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder: :name %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_area :description, placeholder: :description %>
      </p>
      <p>
        <%= f.submit "Save changes", :class => 'button-link' %>
        <%= link_to  'Return', classes_path, :class => 'button-link'%>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2 class="fish-h2">Members</h2>
    <div>
      <%= form_for :member_new, url: class_add_member_path(@student_class) do |f| %>
        <p>
          <%= f.text_field :login, placeholder: "User login" %>
        </p>
        <p>
          <%= f.submit "Add class member", :class => 'button-link' %>
        </p>
      <% end %>
    </div>
    <div class="col-md-12" style="height: 25px;"></div>
    <div>
      <h3 class="fish-h3">Users currently on the list:</h3>
      <% @student_class.users.each do |m| %>
        <div class="col-md-12">
          <div class="col-md-6">
            <%= m.login %>
          </div>
          <div class="col-md-6">
            <%= link_to "Remove", class_remove_member_path(class_id: @student_class.id, user_id: m.id), :method => :post, :class => 'link' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="col-md-2"></div>

FishMash/app/views/classes/index.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
  <h1 class="fish-h1">Student classes</h1>
  <div class="fish-button-bar">
    <%= link_to "Create a new class", new_class_path, :class => 'button-link'%>
  </div>
  <table>
    <tr class="fish-table-header">
      <td>Id</td>
      <td>Name</td>
      <td></td>
    </tr>
    <% if @classes.count == 0 %>
      <tr>
        <td>No classes created.</td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
    <% @classes.each do |student_class| %>
      <tr>
        <td><%= student_class.id %></td>
        <td><%= student_class.name %></td>
        <td><%= link_to "Edit", edit_class_path(student_class) %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="col-md-3"></div>

FishMash/app/views/classes/new.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
  <h1 class="fish-h1">Add a new class</h1>
  <%= form_for :student_class, url: classes_path do |f| %>
    <p>
      <%= f.text_field :name, :placeholder => 'Enter the class name' %>
    </p>
    <p>
      <%= f.text_area :description, :placeholder => 'Enter the class description' %>
    </p>
    <p>
      <%= f.submit "Create", :class => 'button-link' %>
      <%= link_to  'Return', classes_path, :class => 'button-link'%>
    </p>
  <% end %>
</div>
<div class="col-md-3"></div>

FishMash/app/views/classes/show.html.erb
<h1>Class: <% @student_class.name %></h1>
<table border="1">
  <thead>
    <tr>
      <td>Name</td>
      <td>Options</td>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.login %></td>
        <td><%= link_to "Remove", class_remove_member_path(class_id: @student_class.id, user_id: student.id), :method => :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>