FishMash/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'languages/index'
  end

  get 'api' => 'application#api'
  namespace :api, defaults: {format: :json} do
    resources :exams, except: [:create, :delete, :update] do
      post 'start'
      post 'get_question'
      post 'answer'
      get 'summary'
    end
    resources :lists, only: [:index, :show] do
      post 'add'
      post 'remove'
    end
    resources :words, only: [:create]
    resources :languages, only: [:index]
    resources :users do
      collection do
        post 'authenticate'
        post 'set_password'
      end
    end
  end

  resources :wordlists, controller: 'word_lists'
  resources :exams, only: [:index, :new, :create] do
    get 'begin'
    post 'start'
    get 'answer'
    post 'answer', to: 'exams#save_answer'
    get 'summary'
    get 'learn'
    get 'stats'
    post 'get_stats/:class_id', to: 'exams#get_stats'
  end
  resources :users, only: [:show, :create] do
    collection do
      get 'login'
      post 'authenticate'
      get 'logout'
      get 'register'
      get 'profile'
    end

    post 'set_password'
  end
  resources 'classes', except: [:show] do
    post 'add_member'
    post 'remove_member'
  end
  root 'home#index'

end

FishMash/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FishMash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless flash[:errors].blank? %>
  <!-- Errors container -->
  <div class="alert alert-error" role="alert">
    <%= raw flash[:errors] %>
  </div>
<% end %>
<% unless @errors.blank? %>
  <div class="alert alert-error" role="alert">
    <%= raw @errors %>
  </div>
<% end %>

<% unless flash[:success].blank? %>
  <!-- Success messages container -->
  <div class="alert alert-success" role="alert">
    <%= raw flash[:success] %>
  </div>
<% end %>
<% unless @success.blank? %>
  <div class="alert alert-success" role="alert">
    <%= raw @success %>
  </div>
<% end %>

<div class="col-md-12 fish-nav">
  <ul>

    <% if !is_user_logged_in? %>
      <li><%= link_to 'register', register_users_path %></li>
    <% else %>
      <% if get_logged_user.is_teacher? %>
        <li><%= link_to 'classes', classes_path %></li>
      <% end %>
      <li><%= link_to 'exams', exams_path %></li>
      <li><%= link_to 'word lists', wordlists_path %></li>
    <% end %>

    <li class="fish-nav-logo">
      <%= link_to raw(image_tag "logo_fff.svg"), root_url %>
    </li>

    <% if !is_user_logged_in? %>
      <li><%= link_to 'login', login_users_path %></li>
    <% else %>
      <% if get_logged_user.is_teacher? %>
        <li>about</li>
      <% end %>
      <li><%= link_to 'profile', profile_users_path %></li>
      <li><%= link_to 'logout', logout_users_path %></li>
    <% end %>


  </ul>
</div>
<div class="col-md-12 fish-desc">
  CODED AND DESIGNED BY: <span style="color: #2b2b2b">TEN GUYS ONE CODE</span>
</div>

<div>
  <%= yield %>
</div>

</body>
</html>

FishMash/app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FishMash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="blank-layout-body">

<% unless flash[:errors].blank? %>
  <!-- Errors container -->
  <div class="alert alert-error" role="alert">
    <%= raw flash[:errors] %>
  </div>
<% end %>
<% unless @errors.blank? %>
  <div class="alert alert-error" role="alert">
    <%= raw @errors %>
  </div>
<% end %>

<% unless flash[:success].blank? %>
  <!-- Success messages container -->
  <div class="alert alert-success" role="alert">
    <%= raw flash[:success] %>
  </div>
<% end %>
<% unless @success.blank? %>
  <div class="alert alert-success" role="alert">
    <%= raw @success %>
  </div>
<% end %>

  <%= yield %>

</body>
</html>