FishMash/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'languages/index'
  end

  get 'api' => 'application#api'
  namespace :api, defaults: {format: :json} do
    resources :exams, except: [:create, :delete, :update] do
      post 'start'
      post 'get_question'
      post 'answer'
      get 'summary'
    end
    resources :lists, only: [:index, :show] do
      post 'add'
      post 'remove'
    end
    resources :words, only: [:create]
    resources :languages, only: [:index]
    resources :users do
      collection do
        post 'authenticate'
        post 'set_password'
      end
    end
  end

  resources :wordlists, controller: 'word_lists'
  resources :exams, only: [:index, :new, :create] do
    get 'begin'
    post 'start'
    get 'answer'
    post 'answer', to: 'exams#save_answer'
    get 'summary'
    get 'learn'
    get 'stats'
    post 'get_stats/:class_id', to: 'exams#get_stats'
  end
  resources :users, only: [:show, :create] do
    collection do
      get 'login'
      post 'authenticate'
      get 'logout'
      get 'register'
      get 'profile'
    end

    post 'set_password'
  end
  resources 'classes', except: [:show] do
    post 'add_member'
    post 'remove_member'
  end
  root 'home#index'

end

FishMash/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :api_tokens
  has_many :student_class_memberships
  has_many :student_classes, through: :student_class_memberships
  has_many :assesments
  has_many :owned_exams, class_name: 'Exam', foreign_key: :owner_id
  has_many :owned_wordlists, class_name: 'WordList', foreign_key: :owner_id
  has_many :owned_student_classes, class_name: 'StudentClass', foreign_key: :owner_id

  validates :password, presence: true, confirmation: true
  validates :email, presence: true, uniqueness: true
  validates :login, presence: true, uniqueness: true

  def change_password(pass_old, pass_new, pass_new_confirmation)
    return UserCommon::PASS_CHANGE_NOT_EQUAL if pass_new != pass_new_confirmation

    #Old password check
    user = User.find(self.id).try(:authenticate, pass_old)
    if !user
      return UserCommon::PASS_CHANGE_OLD_INVALID
    end

    #Change
    password_params = { password: pass_new, password_confirmation: pass_new_confirmation }
    if user.update(password_params)
      return UserCommon::PASS_CHANGE_SUCCESS
    else
      return UserCommon::PASS_CHANGE_FAILURE
    end
  end

  def get_available_exams
    exams = Array.new
    self.student_classes.each do |student_class|
      exams = exams | student_class.exams
    end
    return exams
  end

  def get_available_wordlists
    wordlists = Array.new
    self.get_available_exams.each do |exam|
      if exam.date_practice_start <= Date.today and exam.date_practice_finish >= Date.today
        wordlists = wordlists | exam.word_lists
      end
    end
    return wordlists
  end

  def is_student?
    return self.user_type == 1
  end

  def is_teacher?
    return self.user_type == 2
  end

  def to_dto
    user_dto = Hash.new
    user_dto[:login] = self.login
    user_dto[:email] = self.email
    user_dto[:created_at] = self.created_at
    user_dto[:updated_at] = self.updated_at
    user_dto[:user_type] = self.user_type

    return user_dto
  end
end

FishMash/app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json, :xml
  before_action :api_authorize, except: [:authenticate]

  def authenticate
    user = User.find_by(login: user_authentication_params[:login]).try(:authenticate, user_authentication_params[:password])
    if !user
      render_status :unauthorized
    else
      token = ApiToken.new
      puts token.inspect
      user.api_tokens.push token
      respond_with token, location: ''
    end
  end

  def show
    respond_with api_get_user.to_dto, location: ''
  end

  def set_password
    user = api_get_user
    pass_params = set_password_params
    result = user.change_password(pass_params[:password_old], pass_params[:password], pass_params[:password_confirmation])
    success = result.equal? UserCommon::PASS_CHANGE_SUCCESS
    result = { success: success, result_status: result  }

    respond_with result, location: ''
  end

  private
    def user_authentication_params
      params.require(:user).permit(:login, :password)
    end

  def set_password_params
    { password_old: params.require(:password_old), password: params.require(:password), password_confirmation: params.require(:password_confirmation) }
  end
end

FishMash/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:profile, :set_password]
  layout 'blank', only: [:login, :authenticate, :register]

  def register
    @user = User.new
  end

  def create
    user_type = user_create_params[:user_type].to_i
    unless user_type == 1 or user_type == 2
      throw 'Invalid user type provided'
    end
    @user = User.new user_create_params
    result = @user.save
    if !@user.save
      @errors = stringify_errors(@user)
      render 'register'
    else
      flash[:success] = 'Account has been successfuly created.'
      redirect_to root_path
    end
  end

  def login
  end

  def authenticate
    user = User.find_by(login: user_login_params[:login]).try(:authenticate, user_login_params[:password])
    if !user
      @errors = 'Invalid login or password provided'
      render 'login'
    else
      set_logged_user_id(user.id)
      flash[:success] = "You've successfuly signed in."
      redirect_to wordlists_path
    end
  end

  def logout
    session.destroy
    flash[:success] = 'You are successfuly logged out.'
    redirect_to root_path
  end

  def profile
    @user = User.find(get_logged_user_id)
  end

  def set_password
    #Routing check
    if params[:user_id].to_i != get_logged_user_id
      flash[:errors] = "Invalid user profile!"
      redirect_to root_path and return
    end

    user = get_logged_user
    result = user.change_password(set_password_params[:password_old], set_password_params[:password], set_password_params[:password_confirmation])
    if result == UserCommon::PASS_CHANGE_SUCCESS
      flash[:success] = 'Password has been successfully changed.'
    elsif result == UserCommon::PASS_CHANGE_NOT_EQUAL
      flash[:errors] = 'Provided passwords were not equal.'
    elsif result == UserCommon::PASS_CHANGE_FAILURE
      flash[:errors] = 'An error occured while changing the password.'
    elsif result == UserCommon::PASS_CHANGE_OLD_INVALID
      flash[:errors] = 'Old password was invalid.'
    end

    redirect_to profile_users_path
  end

  private
    def user_create_params
      params.require(:user).permit(:login, :email, :password, :password_confirmation, :user_type)
    end

    def user_login_params
      params.require(:user).permit(:login, :password)
    end

    def set_password_params
      params.require(:user).permit(:password_old, :password, :password_confirmation)
    end
end

FishMash/app/helpers/api/users_helper.rb
module Api::UsersHelper
end

FishMash/app/helpers/users_helper.rb
module UsersHelper
end

FishMash/app/views/users/login.html.erb
<div class="fish-login-box">

<%= link_to raw(image_tag 'logo.svg'), root_path %>

<%= form_for :user, url: authenticate_users_path do |f| %>
  <div class="form-group">
    <%= f.text_field :login, :placeholder => 'login' %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, :placeholder => 'password' %>
  </div>
  <div class="form-group">
    <%= f.submit "log in" %>
  </div>
<% end %>
</div>

FishMash/app/views/users/profile.html.erb
<div class="col-md-12" style="height: 75px"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
  <div class="col-md-12 fish-user-info">
    <h1 class="fish-h1"><%= @user.login %> profile</h1>
    <div class="col-md-4">
      <div class="fish-profile-photo">
        <%= image_tag 'example_profile.jpg' %> 
      </div>
    </div>
    <div class="col-md-8">
      <p>
        Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor.      
      </p>
    </div>
  </div>
  <div class="col-md-12" style="height: 25px"></div>
  <div class="col-md-6">
    <h2 class="fish-h2">Change password</h2>
    <%= form_for :user, url: user_set_password_path(@user) do |f| %>
      <div class="form-group">
        <%= f.password_field :password_old, :placeholder => 'old password' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => 'new password' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, :placeholder => 'confirm new password' %>
      </div>
      <div class="form-group">
        <%= f.submit "Change password", :class => 'button-link' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h1 class="fish-h1">
      <%= link_to 'My wordlists', wordlists_url %>
    </h1>
    <h1 class="fish-h1">
      <%= link_to 'My exams', exams_url %>
    </h1>
  </div>
</div>
<div class="col-md-3"></div>

FishMash/app/views/users/register.html.erb
<div class="fish-register-box">
  <div class="col-md-6">
    <h1 class="fish-h1">Sign up</h1>
    <h3 class="fish-h3 back-link"><%= link_to 'or go back', root_path%></h3>
    <br />
    <%= form_for @user, url: users_path, method: :post do |f| %>
      <div class="form-group">
        <%= f.text_field :email, :placeholder => 'email' %>
      </div>
      <div class="form-group">
        <%= f.text_field :login, :placeholder => 'login' %>
      </div>
      <div class="form-group">
        <p>
          <%= f.password_field :password, :placeholder => 'password' %>
        </p>
        <p>
          <%= f.password_field :password_confirmation, :placeholder => 'repeat password' %>
        </p>
        <div class="form-group user-type-box">
          <div class="col-md-6 button-link">
            <%= f.radio_button :user_type, '1', checked: true %> Student
          </div>
          <div class="col-md-6 button-link">
            <%= f.radio_button :user_type, '2' %> Teacher
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 desktop">
    <p>
      <%= image_tag 'mobile_add.svg', :style => 'width: 100%; margin-bottom: 0px;'%>
    </p>

  </div>

  <div class="col-md-12" style="text-align: center">
    <h2 class="fish-h2 fish-font-amatic">Check our mobile phone apps!<br>Avaible on Android and Windows Phone</h2>
  </div>

</div>