FishMash/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'languages/index'
  end

  get 'api' => 'application#api'
  namespace :api, defaults: {format: :json} do
    resources :exams, except: [:create, :delete, :update] do
      post 'start'
      post 'get_question'
      post 'answer'
      get 'summary'
    end
    resources :lists, only: [:index, :show] do
      post 'add'
      post 'remove'
    end
    resources :words, only: [:create]
    resources :languages, only: [:index]
    resources :users do
      collection do
        post 'authenticate'
        post 'set_password'
      end
    end
  end

  resources :wordlists, controller: 'word_lists'
  resources :exams, only: [:index, :new, :create] do
    get 'begin'
    post 'start'
    get 'answer'
    post 'answer', to: 'exams#save_answer'
    get 'summary'
    get 'learn'
    get 'stats'
    post 'get_stats/:class_id', to: 'exams#get_stats'
  end
  resources :users, only: [:show, :create] do
    collection do
      get 'login'
      post 'authenticate'
      get 'logout'
      get 'register'
      get 'profile'
    end

    post 'set_password'
  end
  resources 'classes', except: [:show] do
    post 'add_member'
    post 'remove_member'
  end
  root 'home#index'

end

FishMash/app/models/exam.rb
class Exam < ActiveRecord::Base
	has_many :word_list_exams
	has_many :word_lists, through: :word_list_exams
	has_many :student_class_allowed_exams
	has_many :student_classes, through: :student_class_allowed_exams
	has_many :assesments
	belongs_to :owner, class_name: 'User', foreign_key: :owner_id

	validates :name, presence: true, length: { minimum: 1}
	validates :word_count, presence: true
	validates :date_exam_start, presence: true
	validates :date_exam_finish, presence: true
	validates :date_practice_start, presence: true
	validates :date_practice_start, presence: true
	validates :time_limit, presence: true

	def calculate_wordcount
		count = 0
		self.word_lists.each do |word_list|
			count += word_list.words.length
		end

		if count < self.word_count
			return count
		else
			return self.word_count
		end
	end

	def to_dto(options)
		exam_dto = Hash.new
		exam_dto[:id] = self.id
		exam_dto[:name] = self.name
		exam_dto[:date_exam_start] = self.date_exam_start
		exam_dto[:date_exam_finish] = self.date_exam_finish
		exam_dto[:date_practice_start] = self.date_practice_start
		exam_dto[:date_practice_finish] = self.date_practice_finish
		exam_dto[:word_count] = self.word_count
		exam_dto[:time_limit] = self.time_limit

		if options[:user_id]
			exam_dto[:is_finished] = self.is_finished?(options[:user_id])
		end

		exam_dto
	end

	def is_finished?(user_id)
		assesment = self.get_assesment(user_id)
		if assesment.nil?
			return false
		else
			return assesment.finished?
		end
	end

	def start_assesment(user_id)
		existing_assesment = Assesment.where(exam_id: self.id, user_id: user_id).first
		return false unless existing_assesment.nil?

		assesment = Assesment.new(user_id: user_id, exam_id: self.id, time_started: Time.now)
		if assesment.save
			return false if self.word_lists.length.eql? 0 # TODO: Return statuses instead of true or false
			gen_count = self.word_count / self.word_lists.length
			randomizer = Random.new(Time.now.to_i)
			additional_words = 0
			# Generate answer for every word list
			self.word_lists.each do |word_list|
				used_indexes = Array.new
				for i in 1..gen_count
					break if used_indexes.length.eql? word_list.words.length # Prevent endless looping in until loop

					index = 0
					begin
						index = randomizer.rand(word_list.words.length)
					end until !used_indexes.include? index
					used_indexes.push index

					word = word_list.words[index]
					Answer.new(user_id: user_id, assesment_id: assesment.id, word_id: word.id).save
				end
			end
			return assesment
		else
			return false
		end
	end

	def get_assesment(user_id)
		existing_assesment = Assesment.where(exam_id: self.id, user_id: user_id).first
	end
end

FishMash/app/controllers/api/exams_controller.rb
class Api::ExamsController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json, :xml
  before_action :api_authorize
  before_action :validate_assesment, only: [:get_question, :answer, :summary]
  before_action only: [:start, :begin] do # Checks validity of dates for exams
    if ExamCommon.is_start_overdue? params[:exam_id]
      respond_with nil, location: ''
    end
  end
  before_action only: [:learn] do # Checks validity of dates for learning
    if ExamCommon.is_practice_overdue? params[:exam_id]
      respond_with nil, location: ''
    end
  end

  def index
    user = api_get_user
    if user.is_teacher?
      exams = user.owned_exams
    elsif user.is_student?
      exams = user.get_available_exams
    end
    exams_dto = Array.new

    exams.each do |exam|
      exams_dto.push exam.to_dto(user_id: api_get_user.id)
    end

    respond_with exams_dto
  end

  def show
    respond_with Exam.find(params[:id]).to_dto(user_id: api_get_user.id)
  end

  def start
    exam = Exam.find params[:exam_id]
    result_dto = Hash.new
    result_dto[:started] = exam.start_assesment(api_get_user.id)
    result_dto[:message] = result_dto[:started] ? 'Exam succesfuly started' : 'This assesment has already been taken.'
    result_dto[:time_limit] = exam.time_limit

    respond_with result_dto, location: ''
  end

  # Gets the next question to answer
  def get_question
    assesment = Exam.find(params[:exam_id]).get_assesment(api_get_user.id)
    # unless assesment.is_time_exceeded?
    #   finish_exam(assesment)
    #   respond_with Answer.exam_finished_dto, location: '' and return
    # end

    answer = assesment.get_answer
    if answer.nil? # No more questions to answer -> exam's finished.
      finish_exam(assesment)
      respond_with Answer.exam_finished_dto, location: '' and return
    end

    respond_with Answer.to_simple_dto(answer), location: ''
  end

  # Saves the answer in db
  def answer
    assesment = Exam.find(params[:exam_id]).get_assesment(api_get_user.id)
    # unless assesment.is_time_exceeded?
    #   finish_exam(assesment)
    #   respond_with Answer.exam_finished_dto, location: '' and return
    # end

    # TODO: Validate if this is user's question
    answer = Answer.find(params[:answer_id])

    if answer.finished?
      respond_with nil, status: :bad_request
    end

    answer_result = Hash.new
    answer_result[:saved] = answer.provide_answer(params[:answer_text])
    answer_result[:messsage] = answer_result[:saved] ? 'Answer saved' : 'An error occured while saving the answer'

    respond_with answer_result, location: ''
  end

  def summary
    assesment = Exam.find(params[:exam_id]).get_assesment(api_get_user.id)
    respond_with nil, status: :bad_request and return unless assesment.finished?
    answers = Array.new
    assesment.answers.each do |answer|
      answers.push Answer.to_full_dto(answer)
      answers.last[:exam_finished] = true
    end

    respond_with answers, location: ''
  end

  private
    def finish_exam(assesment)
      assesment.finished = true
      assesment.save
    end

    def validate_assesment
  		@exam = Exam.find params[:exam_id]
  		assesment = @exam.get_assesment(api_get_user.id)
  		if assesment.nil?
  			respond_with nil, location: ''
  		end
  	end
end

FishMash/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	before_action :require_login
	before_action :require_teacher, only: [:new, :create, :stats]
	before_action :validate_assesment, only: [:answer, :save_answer, :summary]
	before_action only: [:start, :begin] do # Checks validity of dates for exams
		if ExamCommon.is_start_overdue? params[:exam_id]
			redirect_to exams_path
		end
	end
	before_action only: [:learn] do # Checks validity of dates for learning
		if ExamCommon.is_practice_overdue? params[:exam_id]
			redirect_to exams_path
		end
	end
	before_action only: [:stats] do
		unless ExamCommon.is_owned_by(params[:exam_id], get_logged_user_id)
			redirect_to exams_path
		end
	end

	respond_to :json, :xml, only: [:get_stats] #Helper action for obtaining stats information for stats view.

	MSG_EXAM_TIME_FINISHED = 'Time\'s up. Exam is finished'

	def index
		user = get_logged_user
		if user.is_teacher?
			@exams = user.owned_exams
		elsif user.is_student?
			@exams = user.get_available_exams
		end
	end

	def show
		@exam = Exam.find(params[:id])
	end

	def new
		user = get_logged_user
		@lists = user.owned_wordlists
		@student_classes = user.owned_student_classes
	end

	def learn
		@exam = Exam.find(params[:exam_id])
		@words = Array.new
		@exam.word_lists.each do |wordlist|
			wordlist.words.each do |word|
				word_json = Hash.new
				word_json[:phrase] = word.phrase
				word_json[:meaning] = word.meaning
				@words.push word_json
			end
		end
	end

	def create
		@wordlists = Array.new
		# Removing first, empty element from word_list_id array
		wordlist_id_helper = params[:exam][:word_list_id].drop(1)
		class_list_id_helper = params[:exam][:student_class_id].drop(1)
		wordlists = WordList.find(wordlist_id_helper)
		student_classes = StudentClass.find(class_list_id_helper)
		exam = Exam.new(new_exam_params)
		wordlists.each do |wordlist|
			exam.word_lists.push wordlist
		end
		student_classes.each do |studclass|
			exam.student_classes.push studclass
		end
		exam.owner = get_logged_user

		date_errors = ''

		if exam.date_exam_start > exam.date_exam_finish
			date_errors += 'Exam start date cannot be set after exam finish date<br />'
		end

		if exam.date_practice_start > exam.date_exam_finish
			date_errors += 'Practice start date cannot be set after exam finish date<br />'
		end

		if exam.date_practice_finish > exam.date_exam_finish
			date_errors += 'Practice finish date cannot be set after exam finish date<br />'
		end

		unless date_errors == ''
			flash[:errors] = date_errors
			redirect_to new_exam_path	and return
		end

		if exam.save
			flash[:success] = 'Exam has been successfuly created'
			redirect_to exams_path
		else
			flash[:errors] = stringify_errors(exam)
			redirect_to new_exam_path
		end
	end

	def begin
		@exam = Exam.find params[:exam_id]
	end

	def start
		exam = Exam.find params[:exam_id]
		if exam.start_assesment(get_logged_user_id)
			redirect_to exam_answer_path(exam)
		else
			flash[:errors] = 'This assesment has already been taken.'
			redirect_to exams_path
		end
	end

	def answer
		assesment = @exam.get_assesment(get_logged_user_id)
		@answer = assesment.get_answer
		@finish_timetime = (assesment.time_started + @exam.time_limit.minutes)
		# unless assesment.is_time_exceeded?
		# 	flash[:errors] = MSG_EXAM_TIME_FINISHED
		# 	finish_exam(assesment) and return
		# end

		if @answer.nil? # No more questions to answer -> exam's finished.
			finish_exam(assesment)
		end
	end

	def save_answer
		@assesment = @exam.get_assesment(get_logged_user_id)
		# unless @assesment.is_time_exceeded?
		# 	flash[:errors] = MSG_EXAM_TIME_FINISHED
		# 	finish_exam(@assesment) and return
		# end

		# TODO: Validate if this is user's question.
		answer = Answer.find(params[:answer][:answer_id])
		answer.provide_answer(params[:answer][:answer])

		redirect_to exam_answer_path(@exam)
	end

	def summary
		@assesment = @exam.get_assesment(get_logged_user_id)
	end

	def stats
		@exam = Exam.find params[:exam_id]
	end

	def get_stats
		exam = Exam.find params[:exam_id]
		student_class = (exam.student_classes.select { |stud_class| stud_class.id.equal? params[:class_id].to_i }).first
		if student_class.nil?
			respond_with nil, status: :bad_request, location: ''
		end
		stats = student_class.get_stats(exam.id)
		respond_with stats, location: ''
	end

	private

	def validate_assesment
		@exam = Exam.find params[:exam_id]
		assesment = @exam.get_assesment(get_logged_user_id)
		if assesment.nil?
			flash[:errors] = 'You haven\'t started this assesment yet.'
			redirect_to exams_path and return
		end
	end

	def new_exam_params
		params.require(:exam).permit(:name, :description, :date_practice_start, :date_practice_finish, :date_exam_start, :date_exam_finish, :word_count, :time_limit)
	end

	def finish_exam(assesment)
		assesment.finished = true
		assesment.save
		redirect_to exam_summary_path(@exam)
	end

end

FishMash/app/helpers/api/exams_helper.rb
module Api::ExamsHelper
end

FishMash/app/views/exams/answer.html.erb
<div class="col-md-12" style="height: 75px"></div>
<div class="col-md-3"></div>
<div class="col-md-6 answer">
  <h1 class="fish-h1"><%= @exam.name %></h1>
  <h2 class="fish-h2">Provide translation for
    <p class="answer-word"><%= @answer.word.meaning %></p>
    <!--<p id="time-left">-->
    <!--</p>-->
  </h2>
  <%= form_for :answer, url: exam_answer_path, method: :post do |f| %>
    <p>
      <%= f.text_field :answer, placeholder: 'Type in a foreign meaning' %>
    </p>
    <%= f.hidden_field :answer_id, value: @answer.id %>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>
<div class="col-md-3"></div>
<script type="text/javascript">
//  $(document).ready(function () {
//    setInterval(function () {
//      $('#time-left').empty();
//      var time = countdown(new Date(<%= @finish_time.to_i %>) * 1000);
//      $('#time-left').append(time.toString() + ' left');
//      if (time == 0)
//        location.reload();
//    }, 1000);
//  });
</script>

FishMash/app/views/exams/begin.html.erb
<div class="col-md-12" style="height: 75px"></div>
<div class="col-md-3"></div>
<div class="col-md-6 exam-details">
  <p class="text-center begin-exam-header">
    You are about to begin exam
  <p>
  <h1 class="text-center exam-name"><%= @exam.name %></h1>
  <p class="text-center">
	  <%= link_to "Start", exam_start_path(@exam), method: :post, :class => 'button-link' %>
	  <%= link_to "Return", exams_path, :class => 'button-link' %>
  </p>
</div>
<div class="col-md-3"></div>

FishMash/app/views/exams/index.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-2"></div>
<div class="col-md-8">

  <% if get_logged_user.is_teacher? %>
    <div class="fish-button-bar">
      <%= link_to "Create an exam", new_exam_path, :class => 'button-link' %>
    </div>
  <% end %>
  <p>
    <table>
      <tr class="fish-table-header">
    	 <td>Exam name</td>
    	 <td>Description</td>
    	 <td>Date practice start</td>
       <td>Date practice finish</td>
       <td>Date exam start</td>
       <td>Date exam finish</td>
    	 <td>Word count</td>
       <td></td>
       <td></td>
       <% if get_logged_user.is_teacher? %>
        <td></td>
       <% end %>
      </tr>
      <% if @exams.count == 0 %>
        <tr>
          <td>No exams created.</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
      <% @exams.each do |exam| %>
      	<tr>
      	  <td><%= exam.name %></td>
      	  <td><em><%= exam.description %></em></td>
      	  <td><%= exam.date_practice_start %></em></td>
          <td><%= exam.date_practice_finish %></em></td>
      	  <td><%= exam.date_exam_start %></em></td>
          <td><%= exam.date_exam_finish %></em></td>
          <td><%= exam.word_count %></em></td>
          <td>
            <% unless exam.is_finished?(get_logged_user_id) or ExamCommon.is_start_overdue?(exam.id) %>
              <%= link_to 'Start exam', exam_begin_path(exam) %>
            <% else %>
              <% if exam.date_exam_start > Date.today %>
                Exam can be started after <%= exam.date_exam_start %>
              <% else %>
                <%= link_to 'Show summary', exam_summary_path(exam) %>
              <% end %>
            <% end %>
          </td>
          <td>
            <% unless ExamCommon.is_practice_overdue?(exam.id) %>
              <%= link_to 'Practice', exam_learn_path(exam) %>
            <% end %>
          </td>
          <% if get_logged_user.is_teacher? %>
           <td><%= link_to "Stats", exam_stats_path(exam) %></td>
          <% end %>
      	</tr>
      <% end %>
    </table>
  </p>
</div>
<div class="col-md-2"></div>

FishMash/app/views/exams/learn.html.erb
<div class="col-md-12" style="height: 75px"></div>
<div class="col-md-3"></div>
<div class="col-md-6 learn-form">
  <h2 class="fish-h2 fish-font-amatic">Practice</h2>
  <h1 class="fish-h1"><%= @exam.name %></h1>
  <div class="text-center">
    <p>
      <h3 class="fish-h3">Question:</h3> 
      <span class="fish-h1 fish-font-amatic"" id="learning-question"></span>
    </p>
    <p>
      <input type="text" id="learning-text" />
    </p>
    <p style="padding: 25px;">
      Mistakes: <span id="learning-mistakes">0</span>, Words left: <span id="learning-left">0</span>, Words learned: <span id="learning-learned">0</span>
    </p>
    <p>
      <button type="button" id="learning-submit">Submit</button>
    </p>
  </div>
</div>
<div class="col-md-3"></div>

<script type="text/javascript">
  var wordsSrc = <%= raw @words.to_json %>;
  /**
   * Returns a random integer between min (inclusive) and max (inclusive)
   * Using Math.round() will give you a non-uniform distribution!
   */
  function getRandomInt(min, max) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
  }
</script>

<%= javascript_include_tag 'exam-learn', 'data-turbolinks-track' => true %>

FishMash/app/views/exams/new.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-3"></div>
<div class="col-md-6 fish-exam-form">
    <h1 class="fish-h1">New exam</h1>
    <%= form_for :exam, url: exams_path, action: :create do |f| %>
      <p>
        <%= f.text_field :name, placeholder: "Enter the exam name" %>
      </p>
      <p>
        <%= f.text_area :description, placeholder: "Shortly describe the content of this exam..." %>
      </p>
      <div class="col-md-6">
      <p>
         <%= f.text_field :date_practice_start, placeholder: "Start date of practice", id: 'practice-date-start', :class => 'datepicker' %>
      </p>
      <p>
        <%= f.text_field :date_practice_finish, placeholder: "Finish date of practice", id: 'practice-date-finish', :class => 'datepicker' %>
      </p>
      <p>
        <%= f.text_field :date_exam_start, placeholder: "Start date of exam", id: 'exam-date-start', :class => 'datepicker' %>
      </p>
      <p>
        <%= f.text_field :date_exam_finish, placeholder: "Finish date of exam", id: 'exam-date-finish', :class => 'datepicker' %>
      </p>
      <p>
        <%= f.text_field :word_count, placeholder: "Word count", id: 'word-count' %>
      </p>
      <!--<p>-->
        <%= f.hidden_field :time_limit, placeholder: 'Time limit (in minutes)', id: 'time-imit', value: '0' %>
      <!--</p>-->
      </div>
      <div class="col-md-6">
      <p>
        <%= f.select :word_list_id, @lists.collect { |wordlist| [wordlist.name, wordlist.id] }, {}, multiple: true %>
      </p>
      <p>
        <%= f.select :student_class_id, @student_classes.collect { |student_class| [student_class.name, student_class.id] }, {}, multiple: true %>
      </p>
      </div>
      <div class="col-md-12">
        <%= f.submit "Create an exam", :class => 'button-link' %>
        <%= link_to  'Return', exams_path, :class => 'button-link'%>
      </div>
    <% end %>
    <%= javascript_include_tag 'exams', 'data-turbolinks-track' => true %>
</div>
<div class="col-md-3"></div>

<div class="col-md-12" style="height: 75px;"></div>

FishMash/app/views/exams/stats.html.erb
<style>
  .ct-series-a .ct-slice-pie {
    fill: hsl(138, 56%, 46%);
  }

  .ct-series-b .ct-slice-pie {
    fill: hsl(0, 55%, 54%);
  }

  .ct-series-c .ct-slice-pie {
      fill: hsla(41, 100%, 50%, 1);
  }
</style>


<div class="col-md-12" style="height: 75px"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
  <p>
    <% @exam.student_classes.each do |stud_class| %>
      <a href="#" class="button-link studclass-choose" class-id="<%= stud_class.id %>"><%= stud_class.name %></a>
    <% end %>
  </p>
  <p id="student-results" style="visibility: hidden;">
    <table>
        <tr class="fish-table-header">
          <td>No.</td>
          <td>Student</td>
          <td>Result</td>
        </tr>
        <tbody id="student-results-table">
          <td>Choose class to show statistics for</td>
          <td></td>
          <td></td>
        </tbody>
    </table>
  </p>
  <div class="col-md-12" style="height: 75px"></div>
  <div class="col-md-6">
    <div id="participants-chart" class="ct-chart ct-perfect-fourth">
    </div>
  </div>
  <div class="col-md-6">
    <div id="passed-chart" class="ct-chart ct-perfect-fourth">
    
    </div>
  </div>
</div>
<div class="col-md-3"></div>

<input type="hidden" id="exam-id" value="<%= @exam.id %>" />
<%= javascript_include_tag 'exam-stats', 'data-turbolinks-track' => true %>

FishMash/app/views/exams/summary.html.erb
<div class="col-md-12" style="height: 75px;"></div>
<div class="col-md-3"></div>
<div class="col-md-6">
  <h1 class="fish-h1"><%= @exam.name %></h1>
  <h3 class="summary-subtitle">Summary</h3>

  <table>
    <tr class="fish-table-header">
      <td>Question</td>
      <td>Correct answer</td>
      <td>Provided answer</td>
      <td>Mark</td>
    </tr>

    <% @assesment.answers.each do |answer| %>
    <tr>
      <td> <%= answer.word.meaning %> </td>
      <td> <%= answer.word.phrase %> </td>
      <td> <%= answer.answer %> </td>
      <td>
        <% if answer.passed %>
          <span style="color: green">PASSED</span>
        <% else %>
          <span style="color: red">FAILED</span>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>

  <div class="fish-button-bar">
    <%= link_to  'Return', exams_path, :class => 'button-link'%>
  </div>
</div>
<div class="col-md-3"></div>